# Generated by Django 4.2.6 on 2023-10-27 15:32

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agenzia",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Calciatore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ruolo", models.CharField(max_length=64)),
                ("cognome", models.CharField(max_length=64)),
                ("squadra", models.CharField(max_length=64)),
                ("punteggio", models.IntegerField(default=0)),
                ("mediaFV", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Giocatore",
            fields=[
                (
                    "username",
                    models.CharField(
                        default=application.models.generate_username,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agenzia", models.CharField(max_length=64)),
                ("bilancio", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Iscrizione",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("utente", models.CharField(max_length=64)),
                ("torneo", models.CharField(max_length=64)),
                ("squadra", models.CharField(max_length=64)),
                ("dataIscrizione", models.DateField()),
                ("posizione", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Squadra",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("utente", models.CharField(max_length=64)),
                ("nome", models.CharField(max_length=64)),
                ("ordine", models.CharField(max_length=64)),
                ("p1", models.CharField(max_length=64)),
                ("p2", models.CharField(max_length=64)),
                ("p3", models.CharField(max_length=64)),
                ("d1", models.CharField(max_length=64)),
                ("d2", models.CharField(max_length=64)),
                ("d3", models.CharField(max_length=64)),
                ("d4", models.CharField(max_length=64)),
                ("d5", models.CharField(max_length=64)),
                ("d6", models.CharField(max_length=64)),
                ("d7", models.CharField(max_length=64)),
                ("d8", models.CharField(max_length=64)),
                ("cc1", models.CharField(max_length=64)),
                ("cc2", models.CharField(max_length=64)),
                ("cc3", models.CharField(max_length=64)),
                ("cc4", models.CharField(max_length=64)),
                ("cc5", models.CharField(max_length=64)),
                ("cc6", models.CharField(max_length=64)),
                ("cc7", models.CharField(max_length=64)),
                ("cc8", models.CharField(max_length=64)),
                ("a1", models.CharField(max_length=64)),
                ("a2", models.CharField(max_length=64)),
                ("a3", models.CharField(max_length=64)),
                ("a4", models.CharField(max_length=64)),
                ("a5", models.CharField(max_length=64)),
                ("a6", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Torneo",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("dataInizio", models.DateField()),
                ("dataFine", models.DateField()),
                ("quota", models.IntegerField()),
                ("montepremi", models.IntegerField(default=0)),
            ],
        ),
    ]
