# Generated by Django 4.2.6 on 2023-12-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torneo",
            name="montepremi",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="torneo",
            name="quota",
            field=models.FloatField(),
        ),
    ]
