# Generated by Django 4.2.6 on 2023-12-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0003_remove_squadra_a1_remove_squadra_a2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="squadra",
            name="g1",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="squadra",
            name="g10",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="squadra",
            name="g11",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="squadra",
            name="g2",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="squadra",
            name="g3",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="squadra",
            name="g4",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="squadra",
            name="g5",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="squadra",
            name="g6",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="squadra",
            name="g7",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="squadra",
            name="g8",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="squadra",
            name="g9",
            field=models.CharField(default="", max_length=64),
        ),
    ]
