# Generated by Django 4.2.6 on 2023-12-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0004_squadra_g1_squadra_g10_squadra_g11_squadra_g2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="squadra",
            name="g1",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="squadra",
            name="g10",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="squadra",
            name="g11",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="squadra",
            name="g2",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="squadra",
            name="g3",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="squadra",
            name="g4",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="squadra",
            name="g5",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="squadra",
            name="g6",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="squadra",
            name="g7",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="squadra",
            name="g8",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="squadra",
            name="g9",
            field=models.CharField(max_length=64),
        ),
    ]
