# Generated by Django 4.2.6 on 2023-12-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "application",
            "0005_alter_squadra_g1_alter_squadra_g10_alter_squadra_g11_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iscrizione",
            name="posizione",
        ),
        migrations.AddField(
            model_name="torneo",
            name="concluso",
            field=models.BooleanField(default=False),
        ),
    ]
